services:
  macthing_service:
    build:
      context: ./Services/Matchmaker
      dockerfile: Dockerfile
    env_file:
      - ./Services/Matchmaker/.env
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - GOLANG_VERSION=1.20
      - NODE_VERSION=18
    networks:
      - mynetwork
    depends_on:
      - cache
      - database
  
  cache:
    image: redis:latest
    volumes:
      - cache_data:/data
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  
  database:
    image: mariadb:10.6.22-ubi9
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ROOT_PASSWORD_HASH=your_database
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_RANDOM_ROOT_PASSWORD=your_password
    volumes:
      - database_data:/data
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - mynetwork
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  database_data:
    driver: local
  cache_data:
    driver: local